baseURL = 'https://kleptography.pages.dev/' # Production URL
locale = 'en-US'
title = 'Kleptography'
theme = 'gallery' # Tells Hugo to look inside themes/gallery

[params]
  # Basic settings inherited from the gallery theme
  description = "A minimalist photography portfolio"
  columns = 3 # Grid column layout for albums

[mediaTypes."image/jpeg"]
  suffixes = ["jpg", "jpeg"]

[imaging]
  resampleFilter = "Lanczos"
  quality = 85 # Balanced compression for web delivery


[params.umami]
  enable = true
  scriptUrl = "https://cloud.umami.is/script.js" # Replace if self-hosting
  websiteId = "ba836aee-bdd9-44f5-8dce-48e1cbf4610a"             # Your website ID from Umami

[[menu.footer]]
  name = "500px"
  url = "https://500px.com/p/kleptography?view=photos"
  weight = 10

[[menu.footer]]
  name = "Me"
  url = "https://klepsys.lt"
  weight = 20
